import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { Building2, Eye, EyeOff, KeyRound, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import axios from 'axios';
import { setPageTitle } from '@/store/themeConfigSlice';
import { Company, CompanyPayload, CompanyStatus } from '@/types/company';
import superadminService from '@/services/superadminService';
import { Modal } from '@/components/ui/Modal';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';

const blankForm: CompanyPayload = { name: '', contactEmail: '', password: '', status: 'active' };
const dateTime = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Never';
const errorMessage = (error: unknown) => axios.isAxiosError(error) ? error.response?.data?.message || 'Something went wrong.' : 'Something went wrong.';
const statusBadge = (status: CompanyStatus) => ({ active: 'success', suspended: 'warning', disabled: 'danger' }[status]);

const PasswordInput = ({ id, value, onChange, placeholder, required = false }: { id: string; value: string; onChange: (value: string) => void; placeholder: string; required?: boolean }) => {
  const [visible, setVisible] = useState(false);
  return <div className="relative"><input id={id} type={visible ? 'text' : 'password'} className="form-input w-full pr-10" placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} required={required} minLength={value || required ? 8 : undefined} /><button type="button" className="absolute right-3 top-1/2 -translate-y-1/2 text-white-dark hover:text-primary" onClick={() => setVisible(!visible)} aria-label={visible ? 'Hide password' : 'Show password'}>{visible ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div>;
};

const CompaniesPage = () => {
  const dispatch = useDispatch();
  const [companies, setCompanies] = useState<Company[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [loading, setLoading] = useState(true);
  const [formOpen, setFormOpen] = useState(false);
  const [detail, setDetail] = useState<Company | null>(null);
  const [editing, setEditing] = useState<Company | null>(null);
  const [form, setForm] = useState<CompanyPayload>(blankForm);
  const [saving, setSaving] = useState(false);
  const [passwordCompany, setPasswordCompany] = useState<Company | null>(null);
  const [newCompanyPassword, setNewCompanyPassword] = useState('');
  const [deleteCompany, setDeleteCompany] = useState<Company | null>(null);
  const [actionLoading, setActionLoading] = useState(false);

  const load = async () => { setLoading(true); try { const result = await superadminService.listCompanies({ page, limit: 10, search, status }); setCompanies(result.companies); setTotal(result.pagination.total); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } };
  useEffect(() => { dispatch(setPageTitle('Companies | Superadmin')); }, [dispatch]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 250); return () => window.clearTimeout(timer); }, [page, search, status]);

  const openCreate = () => { setEditing(null); setForm(blankForm); setFormOpen(true); };
  const openEdit = (company: Company) => { setEditing(company); setForm({ name: company.name, contactEmail: company.contactEmail, password: '', status: company.status }); setFormOpen(true); };
  const onChange = (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const company = editing ? await superadminService.updateCompany(editing._id, form) : await superadminService.createCompany(form); if (editing && form.password) await superadminService.resetPassword(company._id, form.password); if (editing && form.status !== editing.status) await superadminService.updateStatus(company._id, form.status || 'active'); toast.success(editing ? 'Company updated.' : 'Company created.'); setFormOpen(false); await load(); } catch (error) { toast.error(errorMessage(error)); } finally { setSaving(false); } };
  const changeStatus = async (company: Company, nextStatus: CompanyStatus) => { try { await superadminService.updateStatus(company._id, nextStatus); toast.success(`Company ${nextStatus === 'active' ? 'reactivated' : nextStatus}.`); await load(); } catch (error) { toast.error(errorMessage(error)); } };
  const resetPassword = async (event: FormEvent) => { event.preventDefault(); if (!passwordCompany) return; setActionLoading(true); try { await superadminService.resetPassword(passwordCompany._id, newCompanyPassword); toast.success('Password reset and active sessions revoked.'); setPasswordCompany(null); setNewCompanyPassword(''); } catch (error) { toast.error(errorMessage(error)); } finally { setActionLoading(false); } };
  const remove = async () => { if (!deleteCompany) return; setActionLoading(true); try { await superadminService.deleteCompany(deleteCompany._id); toast.success('Company deleted.'); setDeleteCompany(null); if (companies.length === 1 && page > 1) setPage(page - 1); else await load(); } catch (error) { toast.error(errorMessage(error)); } finally { setActionLoading(false); } };
  const showDetails = async (id: string) => { try { setDetail(await superadminService.getCompany(id)); } catch (error) { toast.error(errorMessage(error)); } };
  const totalPages = Math.max(1, Math.ceil(total / 10));

  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-black dark:text-white">Companies</h1><p className="mt-1 text-sm text-white-dark">Create and manage platform tenants.</p></div><button className="btn btn-primary" onClick={openCreate}><Plus className="mr-1 h-4 w-4" /> Add company</button></div>
    <div className="panel"><div className="mb-5 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white-dark" /><input className="form-input pl-9" placeholder="Search company or administrator email" value={search} onChange={(event) => { setPage(1); setSearch(event.target.value); }} /></div><select className="form-select max-w-full md:w-48" value={status} onChange={(event) => { setPage(1); setStatus(event.target.value); }}><option value="">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="disabled">Disabled</option></select></div>
      {loading ? <div className="flex h-64 items-center justify-center"><LoadingSpinner size="lg" /></div> : <><div className="table-responsive"><table><thead><tr><th>Company</th><th>Administrator email</th><th>Status</th><th>Last login</th><th>Created</th><th className="text-right">Actions</th></tr></thead><tbody>{companies.map((company) => <tr key={company._id}><td><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center bg-primary/10 text-primary"><Building2 className="h-4 w-4" /></span><p className="font-semibold text-black dark:text-white">{company.name}</p></div></td><td>{company.adminUser?.email || company.contactEmail}</td><td><span className={`badge badge-outline-${statusBadge(company.status)}`}>{company.status}</span></td><td>{dateTime(company.adminUser?.lastLogin)}</td><td>{dateTime(company.createdAt)}</td><td><div className="flex justify-end gap-1"><button title="View details" className="btn btn-sm btn-outline-primary p-2" onClick={() => void showDetails(company._id)}><Eye className="h-4 w-4" /></button><button title="Edit company" className="btn btn-sm btn-outline-secondary p-2" onClick={() => openEdit(company)}><Pencil className="h-4 w-4" /></button><button title="Reset password" className="btn btn-sm btn-outline-warning p-2" onClick={() => { setNewCompanyPassword(''); setPasswordCompany(company); }}><KeyRound className="h-4 w-4" /></button>{company.status === 'active' ? <button title="Suspend company" className="btn btn-sm btn-outline-warning" onClick={() => void changeStatus(company, 'suspended')}>Suspend</button> : <button title="Reactivate company" className="btn btn-sm btn-outline-success" onClick={() => void changeStatus(company, 'active')}>Activate</button>}<button title="Delete company" className="btn btn-sm btn-outline-danger p-2" onClick={() => setDeleteCompany(company)}><Trash2 className="h-4 w-4" /></button></div></td></tr>)}{companies.length === 0 && <tr><td colSpan={6} className="py-12 text-center text-white-dark">No companies match your filters.</td></tr>}</tbody></table></div><div className="mt-5 flex items-center justify-between text-sm"><span className="text-white-dark">{total} {total === 1 ? 'company' : 'companies'}</span><div className="flex items-center gap-2"><button className="btn btn-outline-primary btn-sm" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {totalPages}</span><button className="btn btn-outline-primary btn-sm" disabled={page >= totalPages} onClick={() => setPage(page + 1)}>Next</button></div></div></>}</div>
    <Modal open={formOpen} onOpenChange={setFormOpen} title={editing ? 'Edit company' : 'Create company'} description={editing ? 'Update the company administrator account.' : 'Add a company and its administrator sign-in.'} size="md"><form className="space-y-4" onSubmit={submit}><div><label htmlFor="company-name">Company name</label><input id="company-name" name="name" className="form-input" placeholder="e.g. Acme Recruitment" value={form.name} onChange={onChange} required /></div><div><label htmlFor="contact-email">Administrator email</label><input id="contact-email" name="contactEmail" type="email" className="form-input" placeholder="admin@company.com" value={form.contactEmail} onChange={onChange} required /><p className="mt-1 text-xs text-white-dark">This email is used to sign in.</p></div><div><label htmlFor="company-password">{editing ? 'New password' : 'Password'}</label><PasswordInput id="company-password" value={form.password || ''} onChange={(password) => setForm((current) => ({ ...current, password }))} placeholder={editing ? 'Leave blank to keep the current password' : 'Create a strong password'} required={!editing} /><p className="mt-1 text-xs text-white-dark">Use 8+ characters with uppercase, lowercase, and a number.</p></div><div><label htmlFor="company-status">Status</label><select id="company-status" name="status" className="form-select" value={form.status} onChange={onChange}><option value="active">Active</option><option value="suspended">Suspended</option><option value="disabled">Disabled</option></select></div><div className="flex justify-end gap-3 pt-3"><button type="button" className="btn btn-outline-danger" onClick={() => setFormOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving...' : editing ? 'Save changes' : 'Create company'}</button></div></form></Modal>
    <Modal open={!!detail} onOpenChange={(open) => { if (!open) setDetail(null); }} title={detail?.name || 'Company details'} size="md"><div className="space-y-4">{detail && <><div className="flex h-12 w-12 items-center justify-center bg-primary/10 text-primary"><Building2 /></div><div className="grid grid-cols-2 gap-4 border border-white-light p-4 text-sm dark:border-white-light/10"><div><p className="text-white-dark">Status</p><p className="mt-1 font-semibold capitalize">{detail.status}</p></div><div><p className="text-white-dark">Created</p><p className="mt-1 font-semibold">{dateTime(detail.createdAt)}</p></div><div><p className="text-white-dark">Users</p><p className="mt-1 font-semibold">{detail.metrics?.userCount ?? 0}</p></div><div><p className="text-white-dark">Interviews</p><p className="mt-1 font-semibold">{detail.metrics?.interviewCount ?? 0}</p></div></div><div className="text-sm"><p className="text-white-dark">Administrator email</p><p className="font-semibold">{detail.adminUser?.email || detail.contactEmail}</p><p className="mt-1 text-white-dark">Last login: {dateTime(detail.adminUser?.lastLogin)}</p></div></>}</div></Modal>
    <Modal open={!!passwordCompany} onOpenChange={(open) => { if (!open) { setPasswordCompany(null); setNewCompanyPassword(''); } }} title="Reset company password" description={passwordCompany ? `Set a new password for ${passwordCompany.name}'s administrator account.` : undefined} size="md"><form className="space-y-4" onSubmit={resetPassword}><div><label htmlFor="reset-company-password">New password</label><PasswordInput id="reset-company-password" value={newCompanyPassword} onChange={setNewCompanyPassword} placeholder="8+ characters, mixed case, number" required /><p className="mt-1 text-xs text-white-dark">Existing refresh sessions for this administrator will be revoked.</p></div><div className="flex justify-end gap-3 pt-3"><button type="button" className="btn btn-outline-danger" onClick={() => setPasswordCompany(null)}>Cancel</button><button className="btn btn-warning" disabled={actionLoading}>{actionLoading ? 'Resetting...' : 'Reset password'}</button></div></form></Modal>
    <Modal open={!!deleteCompany} onOpenChange={(open) => { if (!open) setDeleteCompany(null); }} title="Delete company" description={deleteCompany ? `Permanently delete ${deleteCompany.name}?` : undefined} size="md"><div className="space-y-4"><p className="text-sm text-white-dark">This removes the company and its administrator account. Deletion is blocked if the company still has additional users.</p><div className="flex justify-end gap-3 pt-3"><button className="btn btn-outline-primary" onClick={() => setDeleteCompany(null)}>Cancel</button><button className="btn btn-danger" disabled={actionLoading} onClick={() => void remove()}>{actionLoading ? 'Deleting...' : 'Delete company'}</button></div></div></Modal>
  </div>;
};

export default CompaniesPage;
